// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jKzZXKohfoTyafKDm1_l3Uztxr6I3n0',
    appId: '1:370275433451:web:6ad2a1fdf9c6269f5777ae',
    messagingSenderId: '370275433451',
    projectId: 'flashscoccer-fdb9a',
    authDomain: 'flashscoccer-fdb9a.firebaseapp.com',
    storageBucket: 'flashscoccer-fdb9a.firebasestorage.app',
    measurementId: 'G-SGV2FH0RJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPkwk1rgVwAsN-sfpaAvEAkq37ba4MKc',
    appId: '1:370275433451:android:983e9b2d4672ef8f5777ae',
    messagingSenderId: '370275433451',
    projectId: 'flashscoccer-fdb9a',
    storageBucket: 'flashscoccer-fdb9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBppKE8FL-v2x4xTkOKgWmo2BAljoQhxpQ',
    appId: '1:370275433451:ios:54a92a212781753e5777ae',
    messagingSenderId: '370275433451',
    projectId: 'flashscoccer-fdb9a',
    storageBucket: 'flashscoccer-fdb9a.firebasestorage.app',
    iosBundleId: 'com.example.projectmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBppKE8FL-v2x4xTkOKgWmo2BAljoQhxpQ',
    appId: '1:370275433451:ios:54a92a212781753e5777ae',
    messagingSenderId: '370275433451',
    projectId: 'flashscoccer-fdb9a',
    storageBucket: 'flashscoccer-fdb9a.firebasestorage.app',
    iosBundleId: 'com.example.projectmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-jKzZXKohfoTyafKDm1_l3Uztxr6I3n0',
    appId: '1:370275433451:web:b108bcd9ec80be385777ae',
    messagingSenderId: '370275433451',
    projectId: 'flashscoccer-fdb9a',
    authDomain: 'flashscoccer-fdb9a.firebaseapp.com',
    storageBucket: 'flashscoccer-fdb9a.firebasestorage.app',
    measurementId: 'G-WTE8ZQG1GF',
  );
}
